"""empty message

Revision ID: 06597677dd9b
Revises: 7c8abbed38fe
Create Date: 2021-06-26 13:25:50.698273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06597677dd9b'
down_revision = '7c8abbed38fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_consultas_correlativo'), 'consultas', ['correlativo'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultas_correlativo'), table_name='consultas')
    # ### end Alembic commands ###
