"""empty message

Revision ID: 16f4a169cd34
Revises: 581f9883fc89
Create Date: 2021-06-10 12:25:54.991612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f4a169cd34'
down_revision = '581f9883fc89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'admin', ['empresa_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_user_empresa')
        batch_op.create_foreign_key(None, 'admin', ['empresa_id'], ['id'])
        batch_op.drop_column('last_seen')
        batch_op.drop_column('empresa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_user_empresa', ['empresa'], unique=False)
        batch_op.drop_column('empresa_id')
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')

    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
