"""empty message

Revision ID: 1737e4a2c262
Revises: 7b7f9f5875dc
Create Date: 2021-06-10 12:31:41.400259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1737e4a2c262'
down_revision = '7b7f9f5875dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_consultas_empresa_id_admin'), 'admin', ['empresa_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_user_empresa')
        batch_op.create_foreign_key(batch_op.f('fk_user_empresa_id_admin'), 'admin', ['empresa_id'], ['id'])
        batch_op.drop_column('empresa')
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('empresa', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_user_empresa_id_admin'), type_='foreignkey')
        batch_op.create_index('ix_user_empresa', ['empresa'], unique=False)
        batch_op.drop_column('empresa_id')
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')

    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_consultas_empresa_id_admin'), type_='foreignkey')

    # ### end Alembic commands ###
