"""empty message

Revision ID: 342231b35e42
Revises: d3b3a568f57e
Create Date: 2021-06-10 22:07:08.724732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342231b35e42'
down_revision = 'd3b3a568f57e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sii', schema=None) as batch_op:
        batch_op.alter_column('rut',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_index('ix_sii_index')
        batch_op.drop_column('index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sii', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.INTEGER(), nullable=True))
        batch_op.create_index('ix_sii_index', ['index'], unique=False)
        batch_op.alter_column('rut',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
