"""empty message

Revision ID: 362687e1392f
Revises: c3e1fba98b39
Create Date: 2021-06-10 21:52:48.417917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362687e1392f'
down_revision = 'c3e1fba98b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_empresa')
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))
        batch_op.drop_index('ix_empresa_index')
        batch_op.create_unique_constraint(batch_op.f('uq_empresa_rut'), ['rut'])
        batch_op.drop_column('comuna')
        batch_op.drop_column('index')
        batch_op.drop_column('rubro')
        batch_op.drop_column('trabajadores')
        batch_op.drop_column('inicio')
        batch_op.drop_column('tramoventas')

    with op.batch_alter_table('sii', schema=None) as batch_op:
        batch_op.alter_column('rut',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_index('ix_sii_index')
        batch_op.drop_column('index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sii', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.INTEGER(), nullable=True))
        batch_op.create_index('ix_sii_index', ['index'], unique=False)
        batch_op.alter_column('rut',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tramoventas', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('inicio', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('trabajadores', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rubro', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('index', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('comuna', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_empresa_rut'), type_='unique')
        batch_op.create_index('ix_empresa_index', ['index'], unique=False)
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    op.create_table('_alembic_tmp_empresa',
    sa.Column('rut', sa.TEXT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.UniqueConstraint('rut', name='uq_empresa_rut')
    )
    # ### end Alembic commands ###
