"""empty message

Revision ID: 4ac2b3a5c48d
Revises: fbeb98fb7308
Create Date: 2021-06-10 20:55:03.370890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac2b3a5c48d'
down_revision = 'fbeb98fb7308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sii',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('tramoventas', sa.Integer(), nullable=True),
    sa.Column('trabajadores', sa.Integer(), nullable=True),
    sa.Column('inicio', sa.Date(), nullable=True),
    sa.Column('rubro', sa.String(length=200), nullable=True),
    sa.Column('comuna', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sii'))
    )
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_ejecutivo', sa.String(length=120), nullable=True))
        batch_op.drop_constraint('fk_consultas_empresa_id_empresa', type_='foreignkey')
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rut', sa.String(length=20), nullable=True))
        batch_op.drop_index('ix_empresa_email')
        batch_op.drop_index('ix_empresa_username')
        batch_op.create_unique_constraint(batch_op.f('uq_empresa_rut'), ['rut'])
        batch_op.drop_column('email')
        batch_op.drop_column('lastname')
        batch_op.drop_column('empresa')
        batch_op.drop_column('username')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('empresa', sa.String(length=120), nullable=True))
        batch_op.drop_constraint('fk_user_empresa_id_empresa', type_='foreignkey')
        batch_op.drop_column('empresa_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_empresa_id_empresa', 'empresa', ['empresa_id'], ['id'])
        batch_op.drop_column('empresa')
        batch_op.drop_column('es_admin')

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('empresa', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_empresa_rut'), type_='unique')
        batch_op.create_index('ix_empresa_username', ['username'], unique=False)
        batch_op.create_index('ix_empresa_email', ['email'], unique=False)
        batch_op.drop_column('rut')

    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_consultas_empresa_id_empresa', 'empresa', ['empresa_id'], ['id'])
        batch_op.drop_column('empresa_ejecutivo')

    op.drop_table('sii')
    # ### end Alembic commands ###
