"""empty message

Revision ID: 521f06b58769
Revises: 1737e4a2c262
Create Date: 2021-06-10 12:52:23.314500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521f06b58769'
down_revision = '1737e4a2c262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('empresa', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresa'))
    )
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresa_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_empresa_username'), ['username'], unique=True)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_email')
        batch_op.drop_index('ix_admin_username')

    op.drop_table('admin')
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_consultas_empresa_id_admin', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_consultas_empresa_id_empresa'), 'empresa', ['empresa_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_empresa_id_admin', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_empresa_id_empresa'), 'empresa', ['empresa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_empresa_id_empresa'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_empresa_id_admin', 'admin', ['empresa_id'], ['id'])

    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_consultas_empresa_id_empresa'), type_='foreignkey')
        batch_op.create_foreign_key('fk_consultas_empresa_id_admin', 'admin', ['empresa_id'], ['id'])

    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('empresa', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index('ix_admin_username', ['username'], unique=False)
        batch_op.create_index('ix_admin_email', ['email'], unique=False)

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresa_username'))
        batch_op.drop_index(batch_op.f('ix_empresa_email'))

    op.drop_table('empresa')
    # ### end Alembic commands ###
