"""empty message

Revision ID: 794462327085
Revises: 06597677dd9b
Create Date: 2021-06-28 16:26:53.408880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794462327085'
down_revision = '06597677dd9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('estado', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'estado')
    # ### end Alembic commands ###
