"""empty message

Revision ID: 84010ba917ba
Revises: 18d24830a583
Create Date: 2021-06-12 16:55:48.546210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84010ba917ba'
down_revision = '18d24830a583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultas_rut'), ['rut'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultas_rut'))

    # ### end Alembic commands ###
