"""empty message

Revision ID: 94c534ca552b
Revises: faacf5517ab9
Create Date: 2021-06-25 12:07:17.356035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c534ca552b'
down_revision = 'faacf5517ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultas', sa.Column('plazoPago', sa.String(length=50), nullable=True))
    op.add_column('consultas', sa.Column('frecuencia', sa.String(length=50), nullable=True))
    op.drop_column('consultas', 'incumplimientos')
    op.drop_column('consultas', 'cupoUtilizado')
    op.drop_column('consultas', 'nVentas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultas', sa.Column('nVentas', sa.INTEGER(), nullable=True))
    op.add_column('consultas', sa.Column('cupoUtilizado', sa.INTEGER(), nullable=True))
    op.add_column('consultas', sa.Column('incumplimientos', sa.INTEGER(), nullable=True))
    op.drop_column('consultas', 'frecuencia')
    op.drop_column('consultas', 'plazoPago')
    # ### end Alembic commands ###
