"""empty message

Revision ID: 9aa6b84bee94
Revises: 362687e1392f
Create Date: 2021-06-10 21:55:39.729904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa6b84bee94'
down_revision = '362687e1392f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresa')),
    sa.UniqueConstraint('rut', name=op.f('uq_empresa_rut'))
    )
    op.drop_table('_alembic_tmp_empresa')
    with op.batch_alter_table('sii', schema=None) as batch_op:
        batch_op.alter_column('rut',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_index('ix_sii_index')
        batch_op.drop_column('index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sii', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.INTEGER(), nullable=True))
        batch_op.create_index('ix_sii_index', ['index'], unique=False)
        batch_op.alter_column('rut',
               existing_type=sa.TEXT(),
               nullable=True)

    op.create_table('_alembic_tmp_empresa',
    sa.Column('rut', sa.TEXT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.UniqueConstraint('rut', name='uq_empresa_rut')
    )
    op.drop_table('empresa')
    # ### end Alembic commands ###
