"""empty message

Revision ID: a1bc2442d057
Revises: e87f72244c51
Create Date: 2021-06-12 14:57:40.277501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1bc2442d057'
down_revision = 'e87f72244c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('rut', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_empresa'),
    sa.UniqueConstraint('rut', name='uq_empresa_rut')
    )
    # ### end Alembic commands ###
