"""empty message

Revision ID: a79be891f4f8
Revises: ad62817d957e
Create Date: 2021-06-30 01:40:48.914207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79be891f4f8'
down_revision = 'ad62817d957e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultas', 'antiguedad_cli')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultas', sa.Column('antiguedad_cli', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
