"""empty message

Revision ID: a8042174a278
Revises: bf9e9b4e9257
Create Date: 2021-06-26 11:12:15.779651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8042174a278'
down_revision = 'bf9e9b4e9257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suspendidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('razon', sa.String(length=200), nullable=True),
    sa.Column('autoridad', sa.Integer(), nullable=True),
    sa.Column('suspension', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suspendidos')
    # ### end Alembic commands ###
