"""empty message

Revision ID: ad62817d957e
Revises: 794462327085
Create Date: 2021-06-29 13:35:28.555701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad62817d957e'
down_revision = '794462327085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultas', sa.Column('CMF_OK', sa.String(length=2), nullable=True))
    op.add_column('consultas', sa.Column('CARPETA_OK', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultas', 'CARPETA_OK')
    op.drop_column('consultas', 'CMF_OK')
    # ### end Alembic commands ###
