"""empty message

Revision ID: bd76b925c12e
Revises: da9400fb08bc
Create Date: 2021-06-22 13:31:17.871774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd76b925c12e'
down_revision = 'da9400fb08bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultas', sa.Column('cmf_cupo_ctge', sa.Integer(), nullable=True))
    op.add_column('consultas', sa.Column('iva_fecha_ini_act_str', sa.String(length=50), nullable=True))
    op.add_column('consultas', sa.Column('iva_total_ventas_ano_1', sa.Integer(), nullable=True))
    op.add_column('consultas', sa.Column('iva_meses_venta_ano_1', sa.Integer(), nullable=True))
    op.add_column('consultas', sa.Column('iva_total_imp_renta_trab_ano_1', sa.Integer(), nullable=True))
    op.add_column('consultas', sa.Column('iva_meses_imp_renta_trab_ano_1', sa.Integer(), nullable=True))
    op.add_column('consultas', sa.Column('iva_total_compras_ano_1', sa.Integer(), nullable=True))
    op.add_column('consultas', sa.Column('iva_meses_compras_ano_1', sa.Integer(), nullable=True))
    op.add_column('consultas', sa.Column('iva_meses_sin_declaracion_ano_1', sa.Integer(), nullable=True))
    op.add_column('consultas', sa.Column('iva_total_ventas_ano_2', sa.Integer(), nullable=True))
    op.add_column('consultas', sa.Column('iva_meses_venta_ano_2', sa.Integer(), nullable=True))
    op.add_column('consultas', sa.Column('iva_total_imp_renta_trab_ano_2', sa.Integer(), nullable=True))
    op.add_column('consultas', sa.Column('iva_meses_imp_renta_trab_ano_2', sa.Integer(), nullable=True))
    op.add_column('consultas', sa.Column('iva_total_compras_ano_2', sa.Integer(), nullable=True))
    op.add_column('consultas', sa.Column('iva_meses_compras_ano_2', sa.Integer(), nullable=True))
    op.add_column('consultas', sa.Column('iva_meses_sin_declaracion_ano_2', sa.Integer(), nullable=True))
    op.drop_column('consultas', 'iva_total_ventas')
    op.drop_column('consultas', 'iva_total_compras')
    op.drop_column('consultas', 'iva_impuesto_renta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultas', sa.Column('iva_impuesto_renta', sa.FLOAT(), nullable=True))
    op.add_column('consultas', sa.Column('iva_total_compras', sa.FLOAT(), nullable=True))
    op.add_column('consultas', sa.Column('iva_total_ventas', sa.FLOAT(), nullable=True))
    op.drop_column('consultas', 'iva_meses_sin_declaracion_ano_2')
    op.drop_column('consultas', 'iva_meses_compras_ano_2')
    op.drop_column('consultas', 'iva_total_compras_ano_2')
    op.drop_column('consultas', 'iva_meses_imp_renta_trab_ano_2')
    op.drop_column('consultas', 'iva_total_imp_renta_trab_ano_2')
    op.drop_column('consultas', 'iva_meses_venta_ano_2')
    op.drop_column('consultas', 'iva_total_ventas_ano_2')
    op.drop_column('consultas', 'iva_meses_sin_declaracion_ano_1')
    op.drop_column('consultas', 'iva_meses_compras_ano_1')
    op.drop_column('consultas', 'iva_total_compras_ano_1')
    op.drop_column('consultas', 'iva_meses_imp_renta_trab_ano_1')
    op.drop_column('consultas', 'iva_total_imp_renta_trab_ano_1')
    op.drop_column('consultas', 'iva_meses_venta_ano_1')
    op.drop_column('consultas', 'iva_total_ventas_ano_1')
    op.drop_column('consultas', 'iva_fecha_ini_act_str')
    op.drop_column('consultas', 'cmf_cupo_ctge')
    # ### end Alembic commands ###
