"""empty message

Revision ID: bf9e9b4e9257
Revises: fcc0af5183bc
Create Date: 2021-06-26 11:00:53.382223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9e9b4e9257'
down_revision = 'fcc0af5183bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_consultas_correlativo', table_name='consultas')
    op.drop_column('consultas', 'correlativo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultas', sa.Column('correlativo', sa.INTEGER(), nullable=True))
    op.create_index('ix_consultas_correlativo', 'consultas', ['correlativo'], unique=False)
    # ### end Alembic commands ###
