"""empty message

Revision ID: da9400fb08bc
Revises: 84010ba917ba
Create Date: 2021-06-12 16:56:32.721509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9400fb08bc'
down_revision = '84010ba917ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultas_cliente'), ['cliente'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultas_cliente'))

    # ### end Alembic commands ###
