"""empty message

Revision ID: edb9f1b8152f
Revises: cbf7228e5d40
Create Date: 2021-06-10 22:15:33.743335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb9f1b8152f'
down_revision = 'cbf7228e5d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sii', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('rut',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sii', schema=None) as batch_op:
        batch_op.alter_column('rut',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
